# Generated by Django 4.2.4 on 2023-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_id', models.IntegerField(default=0)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_marks', models.DecimalField(decimal_places=2, max_digits=100)),
                ('announcement', models.TextField(default='Add Announcement')),
                ('mcq_question', models.JSONField()),
                ('option_1', models.JSONField()),
                ('option_2', models.JSONField()),
                ('option_3', models.JSONField()),
                ('option_4', models.JSONField()),
                ('mcq_answer', models.JSONField()),
                ('short_question', models.JSONField()),
                ('short_answer', models.JSONField()),
                ('broad_question', models.JSONField()),
                ('broad_answer', models.JSONField()),
                ('voice_question', models.JSONField()),
                ('voice_answer', models.JSONField()),
                ('exam_duration', models.IntegerField(default=0)),
                ('mcq_marks', models.DecimalField(decimal_places=2, default=20.0, max_digits=100)),
                ('short_marks', models.DecimalField(decimal_places=2, default=20.0, max_digits=100)),
                ('broad_marks', models.DecimalField(decimal_places=2, default=40.0, max_digits=100)),
                ('voice_marks', models.DecimalField(decimal_places=2, default=20.0, max_digits=100)),
                ('number_of_mcq', models.IntegerField(default=0)),
                ('number_of_short', models.IntegerField(default=0)),
                ('number_of_broad', models.IntegerField(default=0)),
                ('number_of_voice', models.IntegerField(default=0)),
                ('unknown_face_detection_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('tab_change_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_id', models.IntegerField(default=0)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_marks', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='voice_recordings/')),
            ],
        ),
    ]
