# Generated by Django 4.2.4 on 2023-10-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0002_alter_computerscience_broad_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerscience',
            name='broad_answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='broad_question',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='mcq_answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='mcq_question',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_1',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_2',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_3',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_4',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='short_answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='short_question',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='voice_answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='voice_question',
            field=models.JSONField(),
        ),
    ]
