# Generated by Django 4.2.4 on 2023-10-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0002_rename_course_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_id', models.IntegerField(default=0)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_marks', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
