# Generated by Django 4.2.4 on 2023-10-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0003_computerscience'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerscience',
            name='announcement',
            field=models.TextField(default='Add Announcement'),
        ),
    ]
