# Generated by Django 4.2.4 on 2023-10-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0004_computerscience_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerscience',
            name='broad_answer',
            field=models.TextField(default='Enter'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='broad_question',
            field=models.TextField(default='Enter'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='mcq_answer',
            field=models.CharField(default='Enter', max_length=150),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='mcq_question',
            field=models.TextField(default='Enter'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='option_1',
            field=models.CharField(default='Enter', max_length=150),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='option_2',
            field=models.CharField(default='Enter', max_length=150),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='option_3',
            field=models.CharField(default='Enter', max_length=150),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='option_4',
            field=models.CharField(default='Enter', max_length=150),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='short_answer',
            field=models.TextField(default='Enter'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='short_question',
            field=models.TextField(default='Enter'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='voice_answer',
            field=models.TextField(default='Enter'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='voice_question',
            field=models.TextField(default='Enter'),
        ),
    ]
