# Generated by Django 4.2.4 on 2023-10-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0005_computerscience_broad_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerscience',
            name='broad_answer',
            field=models.TextField(blank=True, default='Enter'),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='broad_question',
            field=models.TextField(blank=True, default='Enter'),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='short_answer',
            field=models.TextField(blank=True, default='Enter'),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='short_question',
            field=models.TextField(blank=True, default='Enter'),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='voice_answer',
            field=models.TextField(blank=True, default='Enter'),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='voice_question',
            field=models.TextField(blank=True, default='Enter'),
        ),
    ]
