# Generated by Django 4.2.4 on 2023-10-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0008_voicerecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerscience',
            name='broad_marks',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='mcq_marks',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='short_marks',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='voice_marks',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=100),
        ),
    ]
