# Generated by Django 4.2.4 on 2023-10-25 05:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0011_alter_computerscience_mcq_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerscience',
            name='mcq_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default='Enter', size=None),
        ),
    ]
