# Generated by Django 4.2.4 on 2023-10-25 05:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0012_alter_computerscience_mcq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerscience',
            name='mcq_answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), default='Enter', size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), default='Enter', size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), default='Enter', size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), default='Enter', size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), default='Enter', size=None),
        ),
    ]
