# Generated by Django 4.2.4 on 2023-10-25 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0014_alter_computerscience_broad_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerscience',
            name='broad_answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default='Enter', size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='broad_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default='Enter', size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='short_answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default='Enter', size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='short_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default='Enter', size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='voice_answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default='Enter', size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='voice_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default='Enter', size=None),
        ),
    ]
