# Generated by Django 4.2.4 on 2023-10-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0015_alter_computerscience_broad_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerscience',
            name='number_of_broad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='number_of_mcq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='number_of_short',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='number_of_voice',
            field=models.IntegerField(default=0),
        ),
    ]
