# Generated by Django 4.2.4 on 2023-10-27 17:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0016_computerscience_number_of_broad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerscience',
            name='mcq_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
