# Generated by Django 4.2.4 on 2023-10-27 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0017_alter_computerscience_mcq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerscience',
            name='broad_answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='broad_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='mcq_answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='option_4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Enter', max_length=150), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='short_answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='short_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='voice_answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='computerscience',
            name='voice_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
