# Generated by Django 4.2.4 on 2023-10-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_System', '0018_alter_computerscience_broad_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerscience',
            name='tab_change_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='unknown_face_detection_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
